# Generated by Django 4.1.3 on 2023-01-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteApp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='image',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
